name: Run Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - server: '7.2.3'
            java-distribution: 'temurin'
            java-version: '8'

#          - server: '7.6.5'
#            java-distribution: 'temurin'
#            java-version: '21'
#
#          - server: 'community-7.6.2'
#            java-distribution: 'temurin'
#            java-version: '17'
#
#          - server: '6.6.6'
#            java-distribution: 'temurin'
#            java-version: '8'

    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          # Version from the matrix is for running tests. Second version is for building the SDK.
          java-version: |
            ${{ matrix.java-version }}
            17

          cache: 'maven'

      - name: Run tests
        timeout-minutes: 40
        env:
          COUCHBASE: ${{ matrix.server }}
        run: |
          TEST_JAVA_HOME=$JAVA_HOME_${{ matrix.java-version }}_X64
          ./mvnw verify --batch-mode -Dmaven.test.failure.ignore=true -Dmaven.javadoc.skip=true -Djvm=${TEST_JAVA_HOME}/bin/java

      - name: Check ResourceLeakDetector results
        run: |
          if grep "LEAK:" target/surefire-reports/*.xml > leaks.txt; then
            cat leaks.txt
            echo "Memory leak detected; see task summary for details" >> $GITHUB_STEP_SUMMARY
            false
          fi

      - name: Publish test results
        run: |
          curl https://raw.githubusercontent.com/couchbaselabs/junit-markdown/refs/heads/main/JunitMarkdown.java --output ${{ runner.temp }}/JunitMarkdown.java
          java ${{ runner.temp }}/JunitMarkdown.java . >> $GITHUB_STEP_SUMMARY

      - name: Remove artifacts from Maven repo so they're not cached
        run: rm -rfv ~/.m2/repository/com/couchbase/client/
